---
- name: install and start apache httpd
  hosts: all
  gather_facts: no
  tasks: 
    # yum install httpd
    - name: Install a package - httpd
      yum:
        name: httpd
        state: latest
    # scp files/index.html ansible#:/var/www/html/index.html
    - name: copy from files/index.html to /var/www/html/index.html
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
    # systemctl enable --now httpd
    - name: start the web service - httpd
      service:
        name: httpd
        state: restarted
        enabled: yes
    # firewall-cmd --permanent --add-service=http
    - name: start the firewalld - firewalld.service
      service:
        name: firewalld
        state: started
        enabled: yes
    - name: Open the service - http(80/tcp)
      firewalld:
        service: http
        state: enabled
        permanent: yes
        immediate: yes
